export const PREFECTURES = [
  '北海道',
  '青森県',
  '岩手県',
  '宮城県',
  '秋田県',
  '山形県',
  '福島県',
  '茨城県',
  '栃木県',
  '群馬県',
  '埼玉県',
  '千葉県',
  '東京都',
  '神奈川県',
  '新潟県',
  '富山県',
  '石川県',
  '福井県',
  '山梨県',
  '長野県',
  '岐阜県',
  '静岡県',
  '愛知県',
  '三重県',
  '滋賀県',
  '京都府',
  '大阪府',
  '兵庫県',
  '奈良県',
  '和歌山県',
  '鳥取県',
  '島根県',
  '岡山県',
  '広島県',
  '山口県',
  '徳島県',
  '香川県',
  '愛媛県',
  '高知県',
  '福岡県',
  '佐賀県',
  '長崎県',
  '熊本県',
  '大分県',
  '宮崎県',
  '鹿児島県',
  '沖縄県',
] as const

export const VEHICLE_PRESETS = [
  { id: 'kei', label: '軽自動車', fuelKmL: 24, example: 'N-BOX・タント' },
  { id: 'compact', label: '小型車', fuelKmL: 20, example: 'フィット・ヤリス' },
  { id: 'sedan', label: '普通車', fuelKmL: 16, example: 'Mazda3・カローラ' },
  { id: 'minivan', label: 'ミニバン', fuelKmL: 14, example: 'ステップワゴン' },
  { id: 'suv', label: 'SUV', fuelKmL: 13, example: 'RAV4・ハリアー' },
  { id: 'large', label: '大型SUV/ミニバン', fuelKmL: 11, example: 'アルファード' },
  { id: 'ev', label: 'EV（電気自動車）', fuelKmL: 7, example: 'リーフ・Model 3' },
  { id: 'custom', label: 'カスタム入力', fuelKmL: 0, example: '燃費を直接入力' },
] as const

export const PREFERENCE_OPTIONS = [
  { id: 'scenic', label: '景観' },
  { id: 'hidden', label: '穴場' },
  { id: 'onsen', label: '温泉' },
  { id: 'view', label: '絶景' },
  { id: 'gourmet', label: 'グルメ' },
  { id: 'experience', label: '体験' },
] as const

export const PLAN_STEPS = [
  { step: 1, label: '出発地・日程' },
  { step: 2, label: 'エリア・人数' },
  { step: 3, label: '詳細設定' },
  { step: 4, label: '確認' },
] as const

export const GENERATION_STEPS = [
  'POI検索中',
  'ルート計算中',
  '費用計算中',
  'AIコメント生成中',
] as const
